#!/usr/bin/env ruby

require_relative './lib/settings'

def get(key)
  if key.nil?
    puts Settings.all
  else
    puts Settings[key]
  end
end

def set(args)
  Settings.with_sync_or_save! { apply_args(args) }
end

def set_local(args)
  apply_args(args)
  Settings.save!
end

def apply_args(args)
  args.each do |arg|
    key, value = arg.split('=')
    if value.nil?
      Settings.delete(key)
    else
      Settings[key] = value
    end
  end
end

def restore
  Settings.restore!
end

case ARGV[0]
when 'get'
  get(ARGV[1])
when 'set'
  set(ARGV.drop(1))
when 'set-local'
  set_local(ARGV.drop(1))
when 'restore'
  restore
else
  raise 'Invalid argument. Must be "get", "set", "set-local" or "restore".'
end
