#!/bin/bash
# m h d m dow
# 0 5 * * 1-5

clear_desktop() {
  OLD_PROJECTS_DIR="$HOME/Desktop/old_projects"
  [[ -d "$OLD_PROJECTS_DIR" ]] || mkdir "$OLD_PROJECTS_DIR"
  mv -f "$HOME/Desktop/"* $OLD_PROJECTS_DIR
}

cd "$(dirname "$0")/.."

# only do this if this computer is marked for data resets
[[ "$( ./aa_data get reset-data )" == "true" ]] || exit 1

# make sure no one is using this computer right now
osascript -e '
tell app "System Events" to display dialog ¬
  "App data and settings are about to be cleared. Continue?" ¬
  buttons {"Continue", "Abort"} ¬
  default button "Abort" ¬
  with title "and a title" ¬
  with icon stop ¬
  giving up after 300 seconds
' | grep 'Abort' && exit 1

# reset the data
cd app_management

chrome_data reset
slack_data reset
iterm_data reset
postgres_data reset

clear_desktop
