#!/bin/bash
# m h d m dow
# 0 5 * * 1-5

empty() {
  rm -rf "$HOME/$1/"*
}

backup_and_empty() {
  OLD_DIR="$HOME/$1/old"
  [[ -d "$OLD_DIR" ]] || mkdir "$OLD_DIR"
  mv -f "$HOME/$1/"* $OLD_DIR
}

cd "$(dirname "$0")/.."

# only do this if this computer is marked for data resets
[[ "$( ./settings get reset-data )" == "true" ]] || exit 1

# make sure no one is using this computer right now
osascript -e '
tell application "System Events" to display dialog ¬
  "App data and settings are about to be cleared. Continue?" ¬
  buttons {"Continue", "Abort"} ¬
  default button "Abort" ¬
  with title "Workstation Reset" ¬
  giving up after 300
' | grep 'Abort' && exit 1

# reset the data
cd app_management

./chrome_data reset
./slack_data reset
./iterm_data reset
./postgres_data reset

empty ".Trash"
empty "Downloads"
backup_and_empty "Desktop"
backup_and_empty "Documents"
