#!/bin/bash
# m h d m dow
#

ADMIN_DIR="$(cd "$( "$(dirname "$0")/.." )" && pwd)"
CHROME_CACHES="$HOME/Library/Caches/Google/Chrome/Default"
CHROME_SETTINGS="$HOME/Library/Application Support/Google/Chrome"
BACKUP_CHROME_SETTINGS="$ADMIN_DIR/cache/Chrome"

# kill chrome
osascript -e 'quit app "Google Chrome"'
sleep 5
pkill 'Google Chrome'

rm -rf "$CHROME_CACHES"/*
rm -rf "$CHROME_SETTINGS"
cp -R "$BACKUP_CHROME_SETTINGS" "$CHROME_SETTINGS"
