#!/bin/bash

fail() {
  echo "$( basename "$0" ) failed: $1" >&2
  exit 1
}

[[ $USER == "root" ]] || fail "must be run as root"

cd "$( dirname "$0" )"

SOURCE="$( cd ../cache && pwd )/asr_image.dmg"

# prepare partition to be restored
./asrdiskutil mount backup || fail "could not mount backup volume"
./asrdiskutil rename backup "AAStudentRestoring" || fail "could not rename backup volume"

# begin restoration
asr restore --source "$SOURCE" \
            --target "/dev/$(./asrdiskutil id backup)" \
            --erase --noprompt \
            || fail "restore process failed"

# rename partitions
# ./asrdiskutil rename root "AAStudentBackup" || fail "could not rename root volume"
./asrdiskutil rename backup "AAStudent" || fail "could not rename restored volume"

# set up files on newly restored partition
./prevent_auto_mount root backup
HOME="$( ./asrdiskutil mount_point backup )$HOME" ../maintenance/update_repos

echo "Restore completed."
