#!/bin/bash

fail() {
  echo "$(basename $0) failed: $1" >&2
  exit 1
}

[[ $USER == 'root' ]] || fail "must be run as root"
[[ -n "$1" ]] || fail 'You must provide the server IP address as the argument.'

SERVER_ADDR="$1"

cd "$(dirname $0)"

# ensure WiFi is off
networksetup -setairportpower en1 off

# prepare partition to be restored
./asrdiskutil mount backup || fail 'could not mount backup volume'
./asrdiskutil rename backup "AAStudentRestoring" || fail 'could not rename backup volume'

# begin restoration
asr restore --source "asr://$SERVER_ADDR" \
            --target "/dev/$(./asrdiskutil id backup)" \
            --erase --noprompt \
            || fail 'restore process failed'

# rename partitions
./asrdiskutil rename root "AAStudentBackup" || fail 'could not rename root volume'
./asrdiskutil rename backup "AAStudent" || fail 'could not rename restored volume'
./prevent_auto_mount root backup
../settings sync
echo "Restore completed."
