#!/bin/bash

fail() {
  echo "$(basename $0) failed: $1" >&2
  exit 1
}

[[ $USER == 'root' ]] || fail "must be run as root"
[[ -n "$1" ]] || fail 'You must provide the server IP address as the argument.'

SERVER_ADDR="$1"

cd "$(dirname $0)"

root="$(./get_volume root)"
restore="$(./get_volume restore)"

# ensure WiFi is off
networksetup -setairportpower en0 off

diskutil rename "$restore" "AAStudentRestoring" || fail 'could not rename restore volume'

asr restore --source "asr://$SERVER_ADDR" \
            --target "$restore" --erase --noprompt \
            || fail 'restore process failed'

diskutil rename "$root" "AAStudentBackup" || fail 'could not rename root volume'
diskutil rename "$restore" "AAStudent" || fail 'could not rename restored volume'
echo "Restore completed."
