#!/bin/bash

cd "$(dirname "$0")"

boot_volume="$(bless -getBoot)"
restored_volume="$(./asrdiskutil id restore)"

if [[ "$boot_volume" = "$restored_volume" ]]; then
  echo "booting correct volume '$boot_volume'"
  exit 0
else
  echo "booting '$boot_volume', but should be booting '$restored_volume'"
  exit 1
fi
