#!/bin/bash

APP="iTerm"
ADMIN_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
DATA="$HOME/Library/Preferences/com.googlecode.iterm2.plist"
BACKUP_DATA="$ADMIN_DIR/cache/$APP.plist"

save() {
  rm -f "$BACKUP_DATA"
  cp -R "$DATA" "$BACKUP_DATA"
}

reset() {
  if pgrep "$APP" > /dev/null; then
    osascript -e "quit application \"$APP\""
    osascript -e "quit application \"Terminal\""
    sleep 5
  fi

  rm -f "$DATA"
  cp -R "$BACKUP_DATA" "$DATA"
  >| "$HOME/.bash_history"
}

case "$1" in
"save")
  save;;
"reset")
  reset;;
*)
  echo 'invalid argument. Must be "save" or "reset".' >&2
  exit 1
  ;;
esac
