#!/bin/bash

get_data_dir() {
  base="$HOME/Library/Application Support/Postgres"
  dir="$( ls "$base" | grep 'var-' | tail -n 1 )"
  echo "$base/$dir"
}

APP="Postgres"
ADMIN_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
DATA="$(get_data_dir)"
BACKUP_DATA="$ADMIN_DIR/cache/$APP"

save() {
  rm -rf "$BACKUP_DATA"
  cp -R "$DATA" "$BACKUP_DATA"
  test -f "$BACKUP_DATA/postmaster.pid" && rm "$BACKUP_DATA/postmaster.pid"
}

reset() {
  rm -rf "$DATA"
  cp -R "$BACKUP_DATA" "$DATA"
}

case "$1" in
"save")
  save;;
"reset")
  reset;;
*)
  echo 'invalid argument. Must be "save" or "reset".' >&2
  exit 1
  ;;
esac
