#!/bin/bash
# custom dotfiles install for appacademy machines

cd "$HOME/.dotfiles"

bin/install_dotfiles <(echo y)

# custom configuration
git config --system --unset credential.helper

echo '
function change_git_authorship {
  git filter-branch -f --env-filter "GIT_AUTHOR_NAME='$1'; GIT_AUTHOR_EMAIL='$2'; GIT_COMMITTER_NAME='$1'; GIT_COMMITTER_EMAIL='$2';"
}' >> ~/.aliases
