#!/bin/bash

source "$HOME/.bash_profile"
cd "$(dirname "$0")"

# ensure computer doesn't go to sleep until script finishes
pmset noidle &

# turn display off
pmset displaysleepnow

./update_repos
./reset_workstation
