#!/usr/bin/env ruby
# requires root privileges

raise 'Must be run as root' unless ENV['USER'] == 'root'

require_relative '../lib/settings'

Settings.restore! unless Settings.local_data?

id = Settings['id']
pod = Settings['pod']
station = Settings['station']
student = Settings['student']

if student
  computer_name = "Student #{student}"
  host_name = "st-#{student}"
elsif pod && station
  computer_name = "Floor #{pod} #{station}"
  host_name = "fl-#{pod}-#{station}"
else
  computer_name = "Unassigned"
  host_name = "un"
end

computer_name = "a/A #{computer_name} (##{id})"
host_name = "aa-#{host_name.downcase.tr(' ', '-')}-id#{id}"

`scutil --set ComputerName "#{computer_name}"`
`scutil --set HostName "#{host_name}"`
`scutil --set LocalHostName "#{host_name}"`
