#!/usr/bin/env ruby

class CronScript
  DEFAULT_CRON_SCHEDULE = "30 4 * * 1-5".freeze
  CRON_SCHEDULE_REGEX = %r((?<schedule>([-,\d*/]+[^\S\n]+){4}[-,\d*/]+)\s*)
  CRONS_DIR = File.expand_path("#{File.dirname(__FILE__)}/../crons").freeze

  attr_reader :path, :schedule

  def self.scripts
    scripts = []
    Dir.foreach(CRONS_DIR) do |file|
      next if file[0] == '.'
      scripts << CronScript.new("#{CRONS_DIR}/#{file}")
    end
    scripts
  end

  def initialize(file)
    @path = File.expand_path(file)
    match = CRON_SCHEDULE_REGEX.match(File.read(@path))
    @schedule = match ? match['schedule'] : DEFAULT_CRON_SCHEDULE
  end

  def to_s
    "#{@schedule} #{@path} 2&>1 > /dev/null"
  end
end

def main
  temp_crontab = "#{CronScript::CRONS_DIR}/.crontab"

  File.open(temp_crontab, 'w') do |f|
    f.puts CronScript.scripts.join("\n")
  end

  `crontab #{temp_crontab}`
  File.delete(temp_crontab)
end

main
