#!/usr/bin/env ruby
require_relative '../lib/launchctl'

HOUR = 4
MINUTE = 45
WEEKDAYS = (1..5)

def set_wake_times
  `pmset repeat wakeorpoweron MTWRF #{_zpad(HOUR)}:#{_zpad(MINUTE)}:00`
end

def _zpad(int)
  '%.02i' % int
end

daemon = UserLaunchAgent.new('nightly-procedure')
daemon.configure(
  Program: File.expand_path("../nightly_procedure", __FILE__),
  UserName: 'appacademy'
)
daemon[:StartCalendarInterval] = WEEKDAYS.map do |weekday|
  { Hour: HOUR, Minute: MINUTE, Weekday: weekday }
end

daemon.install
set_wake_times
