#!/usr/bin/env ruby
require_relative '../lib/launchctl'

daemon = LaunchDaemon.new('boot-procedure')
daemon.configure(
  Program: File.expand_path("../boot_procedure", __FILE__),
  UserName: 'root'
)
puts daemon.to_plist
