#!/usr/bin/env ruby
require_relative '../lib/launchctl'

HOUR = 4
MINUTE = 45
WEEKDAYS = (1..5)

def set_wake_times
  `pmset repeat wakeorpoweron MTWRF #{_zpad(HOUR)}:#{_zpad(MINUTE)}:00`
end

def _zpad(int)
  '%.02i' % int
end

agent = UserLaunchAgent.new('nightly-procedure')
agent.configure(
  Program: File.expand_path("../nightly_procedure", __FILE__),
  UserName: ENV['USER'] == 'root' ? 'appacademy' : ENV['USER']
)
agent[:StartCalendarInterval] = WEEKDAYS.map do |weekday|
  { Hour: HOUR, Minute: MINUTE, Weekday: weekday }
end

agent.install
set_wake_times
