#!/usr/bin/env ruby

require 'plist'

DAEMON_NAME = "com.workstation.nightly-procedure".freeze
DAEMON_FILE = "/Users/appacademy/Library/LaunchAgents/#{DAEMON_NAME}.plist".freeze
SCRIPT = File.expand_path("../nightly_procedure", __FILE__)

HOUR = 4
MINUTE = 45
WEEKDAYS = (1..5)

def set_wake_times
  `pmset repeat wakeorpoweron MTWRF #{_zpad(HOUR)}:#{_zpad(MINUTE)}:00`
end

def _zpad(int)
  '%.02i' % int
end

def schedule
  WEEKDAYS.map do |weekday|
    {
      Hour: HOUR,
      Minute: MINUTE,
      Weekday: weekday
    }
  end
end

plist = {
  Label: DAEMON_NAME,
  Program: SCRIPT,
  StartCalendarInterval: schedule,
  UserName: 'appacademy'
}.to_plist

File.write(DAEMON_FILE, plist)

`launchctl unload #{DAEMON_FILE} 2> /dev/null`
`launchctl load #{DAEMON_FILE}`

set_wake_times
