#!/bin/bash

cd "$(dirname "$0")/.."
source .bash_profile

# ensure computer doesn't go to sleep until script finishes
pmset noidle &

# turn display off
pmset displaysleepnow

# turn wifi off
networksetup -setairportpower en1 off

if ifconfig en0 | grep inet > /dev/null; then
  # network is connected
  maintenance/update_repos
  maintenance/install_dotfiles
  maintenance/reset_workstation
else
  # network is not connected
  maintenance/reset_workstation

  osascript -e '
  tell application "System Events" to display dialog ¬
    "The network is disconnected. Please reconnect the cable." ¬
    buttons {"OK"} ¬
    default button "OK" ¬
    with title "Network Disconnected"'

  exit 1
fi
