#!/bin/bash

cd "$(dirname "$0")/.."

# ensure computer doesn't go to sleep until script finishes
pmset noidle &

# turn display off
pmset displaysleepnow

# turn wifi off
networksetup -setairportpower en0 off

if ping -c 1 google.com > /dev/null; then
  # network is connected
  maintenac/update_repos
  maintenac/install_dotfiles
  maintenac/reset_workstation
else
  # network is not connected
  maintenac/reset_workstation

  osascript -e '
  tell application "System Events" to display dialog ¬
    "The network is disconnected. Please reconnect the cable." ¬
    buttons {"OK"} ¬
    default button "OK" ¬
    with title "Network Disconnected"'

  exit 1
fi
