#!/usr/bin/env ruby

require 'plist'
require_relative './nightly_maintenance_schedule'

DAEMON_NAME = "com.workstation.nightly-maintenance".freeze
DAEMON_FILE = "/Users/appacademy/Library/LaunchAgents/#{DAEMON_NAME}.plist".freeze
SCRIPT = File.expand_path("../../maintenance/nightly_maintenance", __FILE__)

def schedule
  MaintenanceSchedule::WEEKDAYS.map do |weekday|
    {
      Hour: MaintenanceSchedule::HOUR,
      Minute: MaintenanceSchedule::MINUTE,
      Weekday: weekday
    }
  end
end

plist = {
  Label: DAEMON_NAME,
  Program: SCRIPT,
  StartCalendarInterval: schedule,
  UserName: 'appacademy'
}.to_plist

File.write(DAEMON_FILE, plist)

`launchctl unload #{DAEMON_FILE} 2> /dev/null`
`launchctl load #{DAEMON_FILE}`

MaintenanceSchedule.set_wake_times
