#!/bin/bash

DB="/Library/Application Support/com.apple.TCC/TCC.db"
SQL="
INSERT or REPLACE
INTO access
VALUES (
  'kTCCServiceAccessibility',
  'com.apple.RemoteDesktopAgent',
  0, 1, 1, NULL, NULL
)"

sudo sqlite3 "$DB" "$SQL"
