#!/bin/bash

ROOT=$1
DB="$ROOT/Library/Application Support/com.apple.TCC/TCC.db"
SQL="
INSERT or REPLACE
INTO access
VALUES (
  'kTCCServiceAccessibility',
  'com.apple.Terminal',
  0, 1, 1, NULL, NULL
)"

sudo sqlite3 "$DB" "$SQL"
