#!/bin/bash

fail() {
  echo "$(basename $0) failed: $1" >&2
  exit 1
}

[[ $USER == 'root' ]] || fail "must be run as root"

cd "$( dirname "$0" )/.."

setup/clone_repos
maintenance/update_repos
maintentance/install_requirements
maintentance/install_dotfiles

./settings restore &>/dev/null
maintenance/set_hostname
setup/enable_accessibility
launchctl/install
