#!/usr/bin/env ruby

DAEMON_NAME = "com.workstation.set-hostname"
DAEMON_FILE = "/Library/LaunchDaemons/#{DAEMON_NAME}.plist"
SCRIPT = File.expand_path("#{File.dirname(__FILE__)}/set_hostname")

plist = <<-XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>#{DAEMON_NAME}</string>
  <key>Program</key>
  <string>#{SCRIPT}</string>
  <key>RunAtLoad</key>
  <true/>
  <key>UserName</key>
  <string>root</string>
</dict>
</plist>
XML

File.open(DAEMON_FILE, 'w') { |f| f.puts(plist) }
