#!/bin/bash

fail() {
  echo "$(basename $0) failed: $1" >&2
  exit 1
}

[[ $USER == 'root' ]] || fail "must be run as root"

cd "$( dirname "$0" )/.."

sudo -u appacademy setup/clone_repos
sudo -u appacademy maintenance/update_repos
sudo -u appacademy maintenance/install_requirements
sudo -u appacademy maintenance/install_dotfiles
setup/install_dependencies

maintenance/set_hostname
setup/enable_accessibility
launchctl/install
