#!/bin/bash

fail() {
  echo "$(basename $0) failed: $1" >&2
  exit 1
}

[[ $USER == 'root' ]] || fail "must be run as root"

cd "$( dirname "$0" )/.."

/settings restore &>/dev/null
setup/enable_accessibility
sudo -u 'appacademy' setup/disable_chrome_signin_prompt
launchctl/install
