#!/usr/bin/env ruby
# requires root privileges

require 'yaml'

DATA_FILE = "/Users/appacademy/.aa_data.yaml"

data = YAML.load_file(DATA_FILE)
id = data['id']
pod = data['pod']
station = data['station']

computer_name = "AAStudent #{pod} #{station} (##{id})"
host_name = "aa-#{pod.downcase.tr(' ', '-')}-#{station}-id#{id}"

`scutil --set ComputerName "#{computer_name}"`
`scutil --set HostName "#{host_name}"`
`scutil --set LocalHostName "#{host_name}.local"`
