#!/usr/bin/env ruby
# requires root privileges

require '../settings'

Settings.restore! unless Settings.saved?

id = Settings['id']
pod = Settings['pod']
station = Settings['station']

computer_name = "AAStudent #{pod} #{station} (##{id})"
host_name = "aa-#{pod.downcase.tr(' ', '-')}-#{station}-id#{id}"

`scutil --set ComputerName "#{computer_name}"`
`scutil --set HostName "#{host_name}"`
`scutil --set LocalHostName "#{host_name}.local"`
